services:

  app:
    build: .
    container_name: location-collision-app
    volumes:
      - .:/app
    working_dir: /app
    command: pytest
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16
    container_name: sunbird_db
    environment:
      POSTGRES_USER: sunbird
      POSTGRES_PASSWORD: sunbird
      POSTGRES_DB: sunbird_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunbird -d sunbird_db"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: