"""Updated column names

Revision ID: d1f63de4ed74
Revises: 6ceaba2ab7f2
Create Date: 2026-03-09 00:54:35.191124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f63de4ed74'
down_revision: Union[str, Sequence[str], None] = '6ceaba2ab7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('tester_id', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('casino_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('accounts_tester_fkey'), 'accounts', type_='foreignkey')
    op.drop_constraint(op.f('accounts_casino_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'testers', ['tester_id'], ['id'])
    op.create_foreign_key(None, 'accounts', 'casinos', ['casino_id'], ['id'])
    op.drop_column('accounts', 'casino')
    op.drop_column('accounts', 'tester')
    op.add_column('actions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('actions_account_fkey'), 'actions', type_='foreignkey')
    op.drop_constraint(op.f('actions_location_fkey'), 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'actions', 'locations', ['location_id'], ['id'])
    op.drop_column('actions', 'account')
    op.drop_column('actions', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('account', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key(op.f('actions_location_fkey'), 'actions', 'locations', ['location'], ['id'])
    op.create_foreign_key(op.f('actions_account_fkey'), 'actions', 'accounts', ['account'], ['id'])
    op.drop_column('actions', 'location_id')
    op.drop_column('actions', 'account_id')
    op.add_column('accounts', sa.Column('tester', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('casino', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_casino_fkey'), 'accounts', 'casinos', ['casino'], ['id'])
    op.create_foreign_key(op.f('accounts_tester_fkey'), 'accounts', 'testers', ['tester'], ['id'])
    op.drop_column('accounts', 'casino_id')
    op.drop_column('accounts', 'tester_id')
    # ### end Alembic commands ###
