"""Avoid duplicate casinos

Revision ID: e4ec3a3faefb
Revises: d1f63de4ed74
Create Date: 2026-03-09 11:35:44.970516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ec3a3faefb'
down_revision: Union[str, Sequence[str], None] = 'd1f63de4ed74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'casinos', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'casinos', type_='unique')
    # ### end Alembic commands ###
