"""add testers and casinos

Revision ID: ed3a29fd29a7
Revises: a9ea8f32c22a
Create Date: 2026-03-08 17:04:19.687968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3a29fd29a7'
down_revision: Union[str, Sequence[str], None] = 'a9ea8f32c22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('signup_rest', sa.Boolean(), nullable=False),
    sa.Column('deposit_rest', sa.Boolean(), nullable=False),
    sa.Column('play_rest', sa.Boolean(), nullable=False),
    sa.Column('withdrawal_rest', sa.Boolean(), nullable=False),
    sa.Column('network_rest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('assigned_quant', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_quant'], ['quants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testers')
    op.drop_table('casinos')
    # ### end Alembic commands ###
