"""Update casino column

Revision ID: efbb386d148d
Revises: 787c459df8f7
Create Date: 2026-03-16 10:34:29.173840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbb386d148d'
down_revision: Union[str, Sequence[str], None] = '787c459df8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casinos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casinos', 'updated_at')
    # ### end Alembic commands ###
